In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Dell\OneDrive\Documents\DATA ANALYSIS PROJECT\Retail Store Sales & Profitability Analysis\EXCELL\retail_store_sales_profitability_raw.csv")
df

,Transaction_ID,Transaction_Date,Store_ID,Store_Name,City,State,Customer_ID,Customer_Segment,Employee_ID,Employee_Name,...,Sales,Cost,Profit,Payment_Method,Order_Status,Sales_Channel,Profit_Margin,Month,Year,Discount_type
0,RTL10001,03-04-2025,S007,Chennai Store,Chennai,Tamil Nadu,CUST02461,Regular,E001,Amit Sharma,...,171.0,95,76,UPI,Completed,Online Pickup,0.44,April,2025,Medium
1,RTL10002,27-02-2025,S010,Delhi Central,Delhi,Delhi,CUST03396,Regular,E010,Ananya Kulkarni,...,414.0,240,174,UPI,Completed,In-Store,0.42,February,2025,Low
2,RTL10003,10-08-2025,S007,Chennai Store,Chennai,Tamil Nadu,CUST00887,Regular,E007,Akash Gupta,...,202.4,130,72,Debit Card,Completed,Online Pickup,0.36,August,2025,Low
3,RTL10004,03-10-2025,S004,Nagpur Store,Nagpur,Maharashtra,CUST02511,Regular,E011,Vivek Singh,...,116.4,85,31,Cash,Completed,In-Store,0.27,October,2025,Medium
4,RTL10005,02-11-2025,S009,Jaipur Store,Jaipur,Rajasthan,CUST03148,Regular,E012,Kavya Iyer,...,2040.0,1320,720,Credit Card,Completed,In-Store,0.35,November,2025,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,RTL21996,20-01-2025,S002,Andheri Store,Mumbai,Maharashtra,CUST03288,Budget,E005,Karan Joshi,...,101.2,65,36,Cash,Completed,In-Store,0.36,January,2025,Low
11996,RTL21997,03-09-2025,S006,Hyderabad Store,Hyderabad,Telangana,CUST00383,Regular,E005,Karan Joshi,...,467.5,350,118,Debit Card,Completed,In-Store,0.25,September,2025,High
11997,RTL21998,12-06-2025,S006,Hyderabad Store,Hyderabad,Telangana,CUST02151,Regular,E011,Vivek Singh,...,192.0,140,52,UPI,Completed,In-Store,0.27,June,2025,High
11998,RTL21999,18-02-2025,S004,Nagpur Store,Nagpur,Maharashtra,CUST02565,Budget,E009,Rahul Desai,...,3040.0,1800,1240,Credit Card,Completed,In-Store,0.41,February,2025,Medium
11999,RTL22000,05-04-2025,S003,Pune Central,Pune,Maharashtra,CUST00880,Budget,E002,Priya Shah,...,1520.0,1150,370,Cash,Completed,In-Store,0.24,April,2025,Medium

In [7]:
df.head()
df.shape
df.info()
df.describe()
df.columns
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    12000 non-null  str
 1   Transaction_Date  12000 non-null  str
 2   Store_ID          12000 non-null  str
 3   Store_Name        12000 non-null  str
 4   City              12000 non-null  str
 5   State             12000 non-null  str
 6   Customer_ID       12000 non-null  str
 7   Customer_Segment  12000 non-null  str
 8   Employee_ID       12000 non-null  str
 9   Employee_Name     12000 non-null  str
 10  Product_ID        12000 non-null  str
 11  Product           12000 non-null  str
 12  Category          12000 non-null  str
 13  Sub_Category      12000 non-null  str
 14  Quantity          12000 non-null  int64
 15  Unit_Price        12000 non-null  int64
 16  Discount          12000 non-null  float64
 17  Sales             12000 non-null  float64
 18  Cost              12000 non-null  int64
 19  Profit            12000 non-null  int64
 20  Payment_Method    12000 non-null  str
 21  Order_Status      12000 non-null  str
 22  Sales_Channel     12000 non-null  str
 23  Profit_Margin     12000 non-null  float64
 24  Month             12000 non-null  str
 25  Year              12000 non-null  int64
 26  Discount_type     12000 non-null  str
dtypes: float64(3), int64(5), str(19)
memory usage: 2.5 MB

Transaction_ID          str
Transaction_Date        str
Store_ID                str
Store_Name              str
City                    str
State                   str
Customer_ID             str
Customer_Segment        str
Employee_ID             str
Employee_Name           str
Product_ID              str
Product                 str
Category                str
Sub_Category            str
Quantity              int64
Unit_Price            int64
Discount            float64
Sales               float64
Cost                  int64
Profit                int64
Payment_Method          str
Order_Status            str
Sales_Channel           str
Profit_Margin       float64
Month                   str
Year                  int64
Discount_type           str
dtype: object

In [9]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [11]:
#Total sales
total_sale=df.Sales.sum()
total_sale

np.float64(28991314.0)

In [12]:
#Total profit
total_profit=df.Profit.sum()
total_profit

np.int64(9845732)

In [13]:
#Average sales
average_sales=df.Sales.mean()
average_sales

np.float64(2415.9428333333335)

In [14]:
#Median sales
median_sales=df.Sales.median()
median_sales

np.float64(828.0)

In [16]:
#Sales distribution
distrbution=(df.groupby("Category")["Sales"].sum().sort_values(ascending=False))
distrbution

Category
Home             10322578.0
Apparel           5579375.0
Kitchen           5098118.5
Electronics       4364235.8
Stationery        1390517.5
Grocery            879552.8
Personal Care      755244.9
Household          601691.5
Name: Sales, dtype: float64

In [19]:
#Best-performing stores
store=(df.groupby("Store_Name")["Sales"].sum().sort_values(ascending=False).head(3))
store

Store_Name
Downtown Store    3151377.90
Andheri Store     3118624.95
Chennai Store     3033215.10
Name: Sales, dtype: float64

In [22]:
#Lowest-performing stores
store=(df.groupby("Store_Name")["Sales"].sum().sort_values(ascending=True).head(3))
store

Store_Name
Ahmedabad Store      2638606.65
Pune Central         2648145.70
Bengaluru Central    2690339.20
Name: Sales, dtype: float64

In [24]:
#Store profit margins
store=(df.groupby("Store_Name")["Profit_Margin"].sum().sort_values(ascending=False))
store

Store_Name
Downtown Store       451.20
Hyderabad Store      436.23
Chennai Store        433.84
Delhi Central        430.11
Jaipur Store         427.45
Ahmedabad Store      426.50
Andheri Store        425.24
Bengaluru Central    423.10
Nagpur Store         416.54
Pune Central         408.92
Name: Profit_Margin, dtype: float64

In [ ]:
df.c
df.Product

0            LED Bulb
1        Water Bottle
2          Toothpaste
3        Basmati Rice
4         Storage Box
             ...
11995    Garbage Bags
11996           Sugar
11997       Chocolate
11998      Table Lamp
11999     Cooking Oil
Name: Product, Length: 12000, dtype: str

In [30]:
#Best-selling products
store=(df.groupby(["Product","Category"])["Sales"].sum().sort_values(ascending=False).head(10))
store

Product            Category
Office Chair       Home           4141995.0
Study Table        Home           3379090.0
Mixer Grinder      Kitchen        2156595.0
Cookware Set       Kitchen        1683475.0
Headphones         Electronics    1632400.0
Bluetooth Speaker  Electronics    1304982.0
Sneakers           Apparel        1267508.0
Jeans              Apparel        1007776.0
Dress              Apparel         967260.0
Electric Kettle    Kitchen         960855.0
Name: Sales, dtype: float64

In [31]:
#Most profitable products
store=(df.groupby(["Product","Category"])["Profit"].sum().sort_values(ascending=False).head(10))
store

Product            Category
Office Chair       Home           1239495
Study Table        Home           1093590
Mixer Grinder      Kitchen         643195
Headphones         Electronics     552050
Cookware Set       Kitchen         539475
Bluetooth Speaker  Electronics     455782
Sneakers           Apparel         407908
Dress              Apparel         351660
Jeans              Apparel         346276
Electric Kettle    Kitchen         342555
Name: Profit, dtype: int64

In [32]:
#Low-profit products
store=(df.groupby(["Product","Category"])["Profit"].sum().sort_values(ascending=True).head(10))
store

Product         Category
Chips           Grocery          10548
Biscuits        Grocery          11496
Sugar           Grocery          12685
Wheat Flour     Grocery          15165
Basmati Rice    Grocery          18457
Toothpaste      Personal Care    21844
Cooking Oil     Grocery          22455
Garbage Bags    Household        24308
Chocolate       Grocery          32283
Toilet Cleaner  Household        33223
Name: Profit, dtype: int64

In [33]:
#Premium vs Regular vs Budget
df["Customer_Segment"].value_counts()

Customer_Segment
Regular    6721
Budget     2989
Premium    2290
Name: count, dtype: int64

In [34]:
#Spending patterns
spending_pattern=(df.groupby("Customer_Segment")["Sales"].agg(["sum","mean","min","max"]))
spending_pattern

                         sum         mean   min      max
Customer_Segment
Budget             7561378.5  2529.735196  42.5  65000.0
Premium            5294114.9  2311.840568  42.5  55000.0
Regular           16135820.6  2400.806517  42.5  59800.0

In [35]:
#Average transaction value by segment
avg_transaction=(df.groupby("Customer_Segment")["Sales"].mean())
avg_transaction

Customer_Segment
Budget     2529.735196
Premium    2311.840568
Regular    2400.806517
Name: Sales, dtype: float64